# https://github.com/Homebrew/homebrew-bundle

tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/dupes"
tap "homebrew/services"
tap "homebrew/versions"
tap "thoughtbot/formulae"

# Homebrew
# https://github.com/Homebrew/brew/
brew "bash-completion"
brew "ctags"
brew "dockutil"
brew "dos2unix"
brew "git"
brew "glib"
brew "homebrew/dupes/rsync"
brew "htop"
brew "imagemagick"
brew "jpeg"
brew "libevent"
brew "libffi"
brew "libpng"
brew "libssh2"
brew "libtiff"
brew "libtool"
brew "libyaml"
brew "openssl"
brew "pgcli"
brew "pkg-config"
brew "postgresql", service_restart: true
brew "python"
brew "rbenv"
brew "readline"
brew "reattach-to-user-namespace"
brew "redis", service_restart: true
brew "ruby-build"
brew "sqlite"
brew "ssh-copy-id"
brew "the_silver_searcher"
brew "tree"
brew "wget"
brew "xz"
brew "zsh"